In [78]:
#pip install seaborn

necessery libraries

In [79]:
import pandas as pd 
import seaborn as sns

In [80]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [81]:
# load dataset
df = sns.load_dataset("titanic")

visualize the loaded data

In [82]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [83]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [84]:
# seeing data for a specific range
df[120:135]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
120,0,2,male,21.0,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False
121,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
122,0,2,male,32.5,1,0,30.0708,C,Second,man,True,NaN,Cherbourg,no,False
123,1,2,female,32.5,0,0,13.0000,S,Second,woman,False,E,Southampton,yes,True
124,0,1,male,54.0,0,1,77.2875,S,First,man,True,D,Southampton,no,False
125,1,3,male,12.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
126,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
127,1,3,male,24.0,0,0,7.1417,S,Third,man,True,NaN,Southampton,yes,True
128,1,3,female,NaN,1,1,22.3583,C,Third,woman,False,F,Cherbourg,yes,False
129,0,3,male,45.0,0,0,6.9750,S,Third,man,True,NaN,Southampton,no,True
130,0,3,male,33.0,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
131,0,3,male,20.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
132,0,3,female,47.0,1,0,14.5000,S,Third,woman,False,NaN,Southampton,no,False
133,1,2,female,29.0,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
134,0,2,male,25.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [85]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [86]:
df.head

<bound method NDFrame.head of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

drop unnecessery and duplicate columns

In [87]:
# 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
#       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
#      'alive', 'alone'

In [88]:
df = df.drop(["class","who","embark_town","alive"], axis = 1,)

In [89]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,deck,alone
0,0,3,male,22.0,1,0,7.2500,S,True,NaN,False
1,1,1,female,38.0,1,0,71.2833,C,False,C,False
2,1,3,female,26.0,0,0,7.9250,S,False,NaN,True
3,1,1,female,35.0,1,0,53.1000,S,False,C,False
4,0,3,male,35.0,0,0,8.0500,S,True,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True,NaN,True
887,1,1,female,19.0,0,0,30.0000,S,False,B,True
888,0,3,female,NaN,1,2,23.4500,S,False,NaN,False
889,1,1,male,26.0,0,0,30.0000,C,True,C,True
890,0,3,male,32.0,0,0,7.7500,Q,True,NaN,True

Initial analysis

In [90]:
df.isna().sum()

survived        0
pclass          0
sex             0
age           177
sibsp           0
parch           0
fare            0
embarked        2
adult_male      0
deck          688
alone           0
dtype: int64

From this analysis we see that we have the most NAN values in "deck" column and second most is in the "age" column. and "emharked" also have 2 NAN values

In [91]:
df.duplicated().sum()

np.int64(107)

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    str
 3   age         714 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    str
 8   adult_male  891 non-null    bool
 9   deck        203 non-null    category
 10  alone       891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(2)
memory usage: 58.8 KB

In [93]:
df.describe() #describes methematical observations. only works for mathemetical data

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## Clean the data

In [94]:
df.drop_duplicates(inplace=True)

In [95]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,deck,alone
0,0,3,male,22.0,1,0,7.2500,S,True,NaN,False
1,1,1,female,38.0,1,0,71.2833,C,False,C,False
2,1,3,female,26.0,0,0,7.9250,S,False,NaN,True
3,1,1,female,35.0,1,0,53.1000,S,False,C,False
4,0,3,male,35.0,0,0,8.0500,S,True,NaN,True

In [96]:
df.drop(["deck"], axis = 1, inplace=True)

In [97]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,3,male,22.0,1,0,7.2500,S,True,False
1,1,1,female,38.0,1,0,71.2833,C,False,False
2,1,3,female,26.0,0,0,7.9250,S,False,True
3,1,1,female,35.0,1,0,53.1000,S,False,False
4,0,3,male,35.0,0,0,8.0500,S,True,True

In [98]:
df.isna().sum()

survived        0
pclass          0
sex             0
age           106
sibsp           0
parch           0
fare            0
embarked        2
adult_male      0
alone           0
dtype: int64

"age" column has a lot of nans, but as they are a number we can fill them up

In [99]:
df.shape

(784, 10)

Fill the nan value of age

In [100]:
mn = df['age'].mean()
mn

np.float64(29.869351032448375)

In [101]:
df['age'] = df['age'].fillna(mn)

In [102]:
df.isna().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      2
adult_male    0
alone         0
dtype: int64

In [103]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,alone
0,0,3,male,22.0,1,0,7.2500,S,True,False
1,1,1,female,38.0,1,0,71.2833,C,False,False
2,1,3,female,26.0,0,0,7.9250,S,False,True
3,1,1,female,35.0,1,0,53.1000,S,False,False
4,0,3,male,35.0,0,0,8.0500,S,True,True